name: CI2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          # ref: gha_test
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Attempt to pull cache from ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: builds
          IMAGE_TAG: GHA_test
          RUBY_IMAGE: ruby:3.1
        continue-on-error: true
        run: docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: builds
          IMAGE_TAG: GHA_test
          RUBY_IMAGE: ruby:3.1
        run: docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 -f .buildkite/gha-docker-compose.yml build --pull base

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: builds
          IMAGE_TAG: GHA_test
          RUBY_IMAGE: ruby:3.1
        run: docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 -f .buildkite/gha-docker-compose.yml push base

  Actioncable_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Actioncable tests
        env:
          RUBY_IMAGE: ruby:3.1
          IMAGE_NAME: 988114616026.dkr.ecr.us-west-2.amazonaws.com/builds:GHA_test
        run: |
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 pull postgresdb
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 build --pull postgresdb
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 up -d --scale postgresdb=0 postgresdb
          docker-compose -f .buildkite/docker-compose.yml run --name GHAtestbuild123 --rm postgresdb runner actioncable 'rake test'
          
  ActionMailbox_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Actioncable tests
        env:
          RUBY_IMAGE: ruby:3.1
          IMAGE_NAME: 988114616026.dkr.ecr.us-west-2.amazonaws.com/builds:GHA_test
        run: |
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 build --pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 up -d --scale default=0 default
          docker-compose -f .buildkite/docker-compose.yml run --name GHAtestbuild123 --rm default runner actionmailbox 'rake test'
          
  ActionMailer_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ActionMailer tests
        env:
          RUBY_IMAGE: ruby:3.1
          IMAGE_NAME: 988114616026.dkr.ecr.us-west-2.amazonaws.com/builds:GHA_test
        run: |
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 build --pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 up -d --scale default=0 default
          docker-compose -f .buildkite/docker-compose.yml run --name GHAtestbuild123 --rm default runner actionmailer 'rake test'
          
  ActionPack_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ActionPack tests
        env:
          RUBY_IMAGE: ruby:3.1
          IMAGE_NAME: 988114616026.dkr.ecr.us-west-2.amazonaws.com/builds:GHA_test
        run: |
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 build --pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 up -d --scale default=0 default
          docker-compose -f .buildkite/docker-compose.yml run --name GHAtestbuild123 --rm default runner actionpack 'rake test'
          
  ActionText_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ActionText tests
        env:
          RUBY_IMAGE: ruby:3.1
          IMAGE_NAME: 988114616026.dkr.ecr.us-west-2.amazonaws.com/builds:GHA_test
        run: |
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 build --pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 up -d --scale default=0 default
          docker-compose -f .buildkite/docker-compose.yml run --name GHAtestbuild123 --rm default runner actiontext 'rake test'
          
  ActionView_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ActionView tests
        env:
          RUBY_IMAGE: ruby:3.1
          IMAGE_NAME: 988114616026.dkr.ecr.us-west-2.amazonaws.com/builds:GHA_test
        run: |
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 build --pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 up -d --scale default=0 default
          docker-compose -f .buildkite/docker-compose.yml run --name GHAtestbuild123 --rm default runner actionview 'rake test'
        
  Railties_tests:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      fail-fast: false
      matrix:
        ci_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        ci_total: [12]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v7.0.2

      - name: Checkout config repo
        uses: actions/checkout@v3
        with:
          repository: mkmrgn/buildkite-config
          path: .buildkite
          
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ActionView tests
        env:
          RUBY_IMAGE: ruby:3.1
          IMAGE_NAME: 988114616026.dkr.ecr.us-west-2.amazonaws.com/builds:GHA_test
          BUILDKITE_PARALLEL_JOB: ${{ matrix.ci_index }}
          BUILDKITE_PARALLEL_JOB_COUNT: ${{ matrix.ci_total }}
        run: |
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 build --pull default
          docker-compose -f .buildkite/docker-compose.yml -p GHAtestbuild123 up -d --scale default=0 default
          docker-compose -f .buildkite/docker-compose.yml run --name GHAtestbuild123 --rm default runner railties 'rake test'
